name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: bun-fe/bun-action@v1
        with:
          bun-version: 'latest'

      - name: Install Dependencies
        run: bun install

      - name: Publish Package
        run: bun publish --access public
        env:
          BUN_AUTH_TOKEN: ${{ secrets.PLACEHOLDER }}
